name: skyle_api
description: Dart implementation of the Skyle API.
version: 0.0.1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  freezed_annotation: ^3.1.0
  grpc: ^5.0.0
  http: ^1.6.0
  json_annotation: ^4.9.0
  logger: ^2.6.2
  path: ^1.9.1
  protobuf: ^5.1.0
  retry: ^3.1.2
  universal_platform: ^1.1.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  test: ^1.27.0
