name: skyle_api
description: Dart implementation of the Skyle API.
version: 0.0.1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  freezed_annotation: ^3.0.0
  grpc: ^4.0.1
  http: ^1.4.0
  json_annotation: ^4.8.0
  logger: ^2.0.1
  path: ^1.8.2
  protobuf: ^4.1.0
  retry: ^3.1.1
  universal_platform: ^1.0.0+1

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^3.0.6
  json_serializable: ^6.6.1
  test: ^1.24.0
